2022-03-03 13:36:23,944 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-03 13:36:23,945 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Python39\lib\site-packages\instabot\bot\bot.py
2022-03-03 13:36:23,946 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-03 13:36:24,136 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-03 13:36:24,527 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-03 13:36:24,745 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-03 13:36:24,943 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-03 13:36:26,177 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-03 13:36:26,178 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXFL4ndq8oMWDVh7N7itVNUSI8m3HfU4_SRUNaimiAn0KZL20Ep6jU1TdDr-B6QNtCh9Tg/tJhTR6qeUb/","api_path":"/challenge/AXFL4ndq8oMWDVh7N7itVNUSI8m3HfU4_SRUNaimiAn0KZL20Ep6jU1TdDr-B6QNtCh9Tg/tJhTR6qeUb/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-03 13:36:26,178 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-03 13:36:26,179 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-03 13:36:26,181 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
